remote_theme: pmarsceill/just-the-docs
title: "The art of the scholar of letters"


footer_content: "All material developed by Graeme Bird, Sophia Sarro and Neel Smith, and available under the Creative Commons Attribution Share-Alike license <a href=\"https://creativecommons.org/licenses/by-sa/4.0/\">CC BY-SA 4.0 <img height=\"15\" width=\"80\" src=\"https://mirrors.creativecommons.org/presskit/buttons/80x15/png/by-sa.png\" /></a> "
